[2025-02-16T15:18:23.089+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T15:18:23.109+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline_dag.process_data manual__2025-02-16T15:18:17.747792+00:00 [queued]>
[2025-02-16T15:18:23.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline_dag.process_data manual__2025-02-16T15:18:17.747792+00:00 [queued]>
[2025-02-16T15:18:23.117+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-16T15:18:23.128+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_data> on 2025-02-16 15:18:17.747792+00:00
[2025-02-16T15:18:23.134+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1008) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T15:18:23.136+0000] {standard_task_runner.py:63} INFO - Started process 1010 to run task
[2025-02-16T15:18:23.136+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline_dag', 'process_data', 'manual__2025-02-16T15:18:17.747792+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpziy23rcn']
[2025-02-16T15:18:23.138+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask process_data
[2025-02-16T15:18:23.178+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline_dag.process_data manual__2025-02-16T15:18:17.747792+00:00 [running]> on host dfa5576bf540
[2025-02-16T15:18:23.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T15:18:17.747792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T15:18:17.747792+00:00'
[2025-02-16T15:18:23.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T15:18:23.299+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-16T15:18:23.300+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T15:18:23.308+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline_dag, task_id=process_data, run_id=manual__2025-02-16T15:18:17.747792+00:00, execution_date=20250216T151817, start_date=20250216T151823, end_date=20250216T151823
[2025-02-16T15:18:23.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-16T15:18:23.372+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-16T15:18:23.374+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
