[2025-02-16T16:02:19.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T16:02:19.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:02:19.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:02:19.684+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-16T16:02:19.696+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-15 12:00:00+00:00
[2025-02-16T16:02:19.707+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1611) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T16:02:19.709+0000] {standard_task_runner.py:63} INFO - Started process 1620 to run task
[2025-02-16T16:02:19.710+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_apod_pipeline', 'create_table', 'scheduled__2025-02-15T12:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/nasa_pipeline_dag.py', '--cfg-path', '/tmp/tmp8axt3oaq']
[2025-02-16T16:02:19.713+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask create_table
[2025-02-16T16:02:19.784+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [running]> on host dfa5576bf540
[2025-02-16T16:02:19.923+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nasa_apod_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T12:00:00+00:00'
[2025-02-16T16:02:19.925+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T16:02:19.940+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS nasa_images (
            id SERIAL PRIMARY KEY,
            date TEXT,
            title TEXT,
            explanation TEXT,
            url TEXT,
            media_type TEXT
        );
        
[2025-02-16T16:02:19.949+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:02:19.958+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:02:23.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T16:02:23.699+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "posgres" to address: Name or service not known

[2025-02-16T16:02:23.713+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nasa_apod_pipeline, task_id=create_table, run_id=scheduled__2025-02-15T12:00:00+00:00, execution_date=20250215T120000, start_date=20250216T160219, end_date=20250216T160223
[2025-02-16T16:02:23.725+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task create_table (could not translate host name "posgres" to address: Name or service not known
; 1620)
[2025-02-16T16:02:23.743+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-16T16:02:23.752+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-02-16T16:02:23.765+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T16:02:23.767+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-16T16:06:21.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T16:06:21.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:06:21.985+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:06:21.986+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-16T16:06:21.997+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-15 12:00:00+00:00
[2025-02-16T16:06:22.004+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1702) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T16:06:22.006+0000] {standard_task_runner.py:63} INFO - Started process 1705 to run task
[2025-02-16T16:06:22.005+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_apod_pipeline', 'create_table', 'scheduled__2025-02-15T12:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/nasa_pipeline_dag.py', '--cfg-path', '/tmp/tmpitt_fnfw']
[2025-02-16T16:06:22.008+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask create_table
[2025-02-16T16:06:22.053+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [running]> on host dfa5576bf540
[2025-02-16T16:06:22.133+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nasa_apod_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T12:00:00+00:00'
[2025-02-16T16:06:22.135+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T16:06:22.148+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS nasa_images (
            id SERIAL PRIMARY KEY,
            date TEXT,
            title TEXT,
            explanation TEXT,
            url TEXT,
            media_type TEXT
        );
        
[2025-02-16T16:06:22.156+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:06:22.164+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:06:25.888+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T16:06:25.892+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "posgres" to address: Name or service not known

[2025-02-16T16:06:25.918+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nasa_apod_pipeline, task_id=create_table, run_id=scheduled__2025-02-15T12:00:00+00:00, execution_date=20250215T120000, start_date=20250216T160621, end_date=20250216T160625
[2025-02-16T16:06:25.934+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task create_table (could not translate host name "posgres" to address: Name or service not known
; 1705)
[2025-02-16T16:06:25.957+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-16T16:06:25.966+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-02-16T16:06:25.978+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T16:06:25.981+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-16T16:13:00.624+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T16:13:00.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:13:00.667+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:13:00.668+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-16T16:13:00.684+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-15 12:00:00+00:00
[2025-02-16T16:13:00.693+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1810) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T16:13:00.698+0000] {standard_task_runner.py:63} INFO - Started process 1825 to run task
[2025-02-16T16:13:00.695+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_apod_pipeline', 'create_table', 'scheduled__2025-02-15T12:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/nasa_pipeline_dag.py', '--cfg-path', '/tmp/tmpg4rhwfe9']
[2025-02-16T16:13:00.712+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask create_table
[2025-02-16T16:13:00.819+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [running]> on host dfa5576bf540
[2025-02-16T16:13:00.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nasa_apod_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T12:00:00+00:00'
[2025-02-16T16:13:00.947+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T16:13:00.962+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS nasa_images (
            id SERIAL PRIMARY KEY,
            date TEXT,
            title TEXT,
            explanation TEXT,
            url TEXT,
            media_type TEXT
        );
        
[2025-02-16T16:13:00.975+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:13:00.984+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:13:00.989+0000] {sql.py:487} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS nasa_images (
            id SERIAL PRIMARY KEY,
            date TEXT,
            title TEXT,
            explanation TEXT,
            url TEXT,
            media_type TEXT
        );
        , parameters: None
[2025-02-16T16:13:00.991+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T16:13:01.004+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nasa_apod_pipeline, task_id=create_table, run_id=scheduled__2025-02-15T12:00:00+00:00, execution_date=20250215T120000, start_date=20250216T161300, end_date=20250216T161301
[2025-02-16T16:13:01.041+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-16T16:13:01.051+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-02-16T16:13:01.064+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T16:13:01.066+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
